services:
  workspace:
    container_name: workspace-container
    build:
      context: ./docker/workspace
    ports:
      - 8080:8080
    volumes:
      - ../:/home/app/workspace:cached
    tty: true
    working_dir: /workspace
  
  mysql:
    platform: linux/amd64
    container_name: mysql-container
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      # - ./docker/mysql/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./.docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOK_API_DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      MYSQL_DATABASE: ${BOOK_API_DB_DATABASE:-dev}
      MYSQL_USER: ${BOOK_API_DB_USER:-mysql}
      MYSQL_PASSWORD: ${BOOK_API_DB_PASSWORD:-thisIsReallyStrongPassword123}